name: Check Terminal Size

on:
  push:

jobs:
  check-size:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run terminal size check
        run: |
          echo "Running terminal size check..."
          python3 terminal_size.py
