name: Setup Android Command Line Tools

on:
  workflow_dispatch:

jobs:
  setup-android-tools:
    runs-on: ubuntu-latest

    steps:
      - name: Create SDK directory
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools

      - name: Download Android Command Line Tools
        run: |
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q commandlinetools-linux-11076708_latest.zip
          mv cmdline-tools latest

      - name: Set ANDROID_HOME and PATH
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Download CPython source
        run: |
          git clone --branch main https://github.com/python/cpython.git
          cd cpython
          git submodule update --init --recursive

      - name: Build CPython for Android and Host
        run: |
          cd cpython/Android
          ./android.py configure-build
          ./android.py make-build
          ./android.py configure-host HOST
          ./android.py make-host HOST

      - name: List files
        run: |
          ls -la
